// Loading, Error
export const LOADING_STATUS = 'LOADING_STATUS';
export const USER_DETAILS = "USER_DETAILS"
export const GET_USERS = "GET_USERS"
export const LATEST_TRANSACTIONS = "LATEST_TRANSACTIONS"
export const USER_TRANSACTIONS = "USER_TRANSACTIONS"
export const USER_NEXT_TRANSACTIONS = "USER_NEXT_TRANSACTIONS"
export const USER_ACCOUNT_CLEARED = "USER_ACCOUNT_CLEARED"

export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ALL = 'CLEARALL';
